name: ShopPluginMoney
main: com.example.shoppluginmoney.ShopPluginMoney
version: 1.0.0
api-version: 1.21
commands:
  shoppay:
    description: 指定プレイヤーにお金を送るコマンド
  selloff:
    description: 売却モードを切り替えるコマンド
  sell:
    description: アイテムを売却するコマンド
  money:
    description: 所持金を確認するコマンド
